name: negotiation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=2.0.0
  - deap=1.4.3
  - flask-socketio=5.5.1
  - eventlet=0.40.0
  - pyyaml=6.0.2
  - pip
  - pip:
      - scoop==0.7.2.0